version: "3.8"

services:
  mongodb:
    image: mongo:6.0          # MongoDB 6 - compatible con CPUs sin AVX2
    container_name: workflow_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: workflow_db
    volumes:
      - mongo_data:/data/db   # Datos persistentes entre reinicios

volumes:
  mongo_data:


