spring.application.name=workflow

server.port=8080
server.servlet.context-path=/api

# MongoDB configuration
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb+srv://Douglas:75399036Dps@primerparcial.global.mongocluster.cosmos.azure.com/workflow_db?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000}
spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE:workflow_db}
spring.autoconfigure.exclude=de.flapdoodle.embed.mongo.spring.autoconfigure.EmbeddedMongoAutoConfiguration

logging.level.com.workflow=DEBUG