spring.data.mongodb.uri=${MONGO_URI:mongodb+srv://padilladouglas6_db_user:etLbm3AFS9OdPKap@cluster0.djqhv0m.mongodb.net/workflow_db?appName=Cluster0&retryWrites=true&w=majority}
spring.data.mongodb.database=workflow_db
spring.autoconfigure.exclude=de.flapdoodle.embed.mongo.spring.autoconfigure.EmbeddedMongoAutoConfiguration
