spring.application.name=workflow

server.port=8080
server.servlet.context-path=/api

# MongoDB configuration
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE}

logging.level.com.workflow=DEBUG